//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spottinglog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SightingList
    {
        public int Sightingid { get; set; }
        public string Registration { get; set; }
        public string Airline { get; set; }
        public string AircraftType { get; set; }
        public string MSN { get; set; }
        public string PhotoCode { get; set; }
        public Nullable<int> SpottingTrip { get; set; }
        public string Notes { get; set; }
        public string FullName { get; set; }
        public string Airport { get; set; }
        public string TripDescription { get; set; }
        public Nullable<System.DateTime> DateofTrip { get; set; }
        public string Comments { get; set; }
        public string Country { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
