//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spottinglog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        public long ID { get; set; }
        public string LoginID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string eMail { get; set; }
        public Nullable<bool> SysAdmin { get; set; }
        public Nullable<bool> ResetPassword { get; set; }
        public Nullable<int> DealerID { get; set; }
        public string TextExtra1 { get; set; }
        public string TextExtra2 { get; set; }
        public Nullable<double> FloatExtra1 { get; set; }
        public Nullable<double> FloatExtra2 { get; set; }
        public Nullable<int> IntExtra { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
        public Nullable<int> RecUser { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string CompanyCode { get; set; }
        public Nullable<int> UserRoleId { get; set; }
        public Nullable<bool> IsSearch { get; set; }
        public Nullable<bool> IsPrint { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsSave { get; set; }
        public Nullable<int> TrnFlag { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> PassWordExpiryDate { get; set; }
        public Nullable<bool> ApprovalStatus { get; set; }
    }
}
