//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spottinglog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAirport
    {
        public int Airportid { get; set; }
        public Nullable<int> Countryid { get; set; }
        public string Airport { get; set; }
    }
}
