//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spottinglog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSpottingTrip
    {
        public int TripId { get; set; }
        public string Country { get; set; }
        public string Airport { get; set; }
        public Nullable<System.DateTime> DateofTrip { get; set; }
        public string Comments { get; set; }
        public Nullable<int> UserID { get; set; }
        public string TripDescription { get; set; }
    }
}
